### ISSUE TITLE
Installing MySQL?

### ISSUE THREAD

**Issue by ruppalsingh** [1and1internet/ubuntu-16-apache-php-7.0#20]
Hi,

I'm new to Docker and have pulled in this image and started a container. Is there any way to install MySQL on the container? The following understandably does not work for me:

```
$ apt-get install mysql-server
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
```

I suppose the cause for this is in the readme though I'm not sure:

```
Please note this image is explictly intended to be run as a non-privileged user. Ensure you specify a user id (UID) other than zero when you run it. Running as root will not function.
```

Will the Dockerfile itself need to edited with instructions to install MySQL and then a new image created?

**Comment by brianwilkinson** [comment]
Hi

You are correct - running as non-root is preventing apt-get install from working. Better to create a new image that has FROM this image and install extra packages that way.

Regards

**Comment by ruppalsingh** [comment]
Thanks for the prompt response and help.

I think I understand what needs to be done now. :)
