### ISSUE TITLE
AH00558: apache2: Could not reliably determine the server's fully qualified domain name

### ISSUE THREAD

**Issue by imranrazakhan** [1and1internet/ubuntu-16-apache-php-7.0#25]
I am using this dockerfile in kubernetes and getting below error

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.129.1.215. Set the 'ServerName' directive globally to suppress this message
--

**Comment by brianwilkinson** [comment]
It's a fairly standard apache warning seen when ServerName isn't set. Apache still works in the way we intended.
